SET FOREIGN_KEY_CHECKS=0; DROP DATABASE production; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP DATABASE sales; SET FOREIGN_KEY_CHECKS=1;
-- SET FOREIGN_KEY_CHECKS=0; DROP DATABASE csv; SET FOREIGN_KEY_CHECKS=1;
-- use csv;
-- DELETE FROM sampledata;
